version: '3'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  postgres-db-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: jira_test
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  myapp:
    image: jira-1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/jira
      SPRING_DATASOURCE_USERNAME: jira
    depends_on:
      - postgres-db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
